# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4851574e38927d161eb292e8d3793634d58146715a040fbbfcc4b640f43e54b37c22ebdf304279ed33928afa45158c54684e793e46b831060675ffa9262a12f0

test:
  secret_key_base: 89db4990467a876af35202be2cfcc96f6c7a977a9322b20c9dae241bfc581d813d434cd77df923d79e794c0f139ee25c42c8f647d3520f7180fa7faaeea66da8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
